### PR TITLE
Added forgotten source code.

### PR DESCRIPTION
**Pull request by ghost**
You forgot to add your source code to your repo. I've done it for you.

You can thank me later :)

### CODE REVIEW

**Comment by ddevault** [comment]
+1

**Comment by kierenj** [comment]
...DevKit isn't open source.  You've reverse-engineered this, which is against the terms of use - and included the source to other components, like SmartAssembly, which I'm pretty sure I can't host the source for.

This would have taken effort better spent on working on the DCPUToolchain IDE..

**Comment by ddevault** [comment]
Why don't you report it to GitHub and draw attention to your repository, which is hosted against their ToS?

**Comment by kierenj** [comment]
Hi Drew, I already emailled them directly about hosting DevKit without source code.  They replied saying it's absolutely fine.  I emplore you with all my might to email them directly and see what they say.  It would make my day.

**Comment by ghost** [comment]
> You've reverse-engineered this, which is against the terms of use

You've hosted binaries without source, which is against the terms of use

**Comment by Mause** [comment]
Er, just trying to be an equalizer here.
Can @mrout and @SirCmpwn please state the section of the Terms of Service they are referring to?

**Comment by kierenj** [comment]
It doesn't exist. They are trolling. As I said I checked with GitHub directly months ago and they almost laughed at the idea of there being a problem. Basically trying to bully me any way they can. Very sad.

**Comment by ghost** [comment]
It very strictly says that github is free for open source projects only.

On Thu, Dec 27, 2012 at 11:31 PM, Kieren Johnstone <notifications@github.com

**Comment by Mause** [comment]
@mrout we are either looking at different terms of service's, or you should be yelling at notch; telling him that he has to open source 0x10c XD

**Comment by kierenj** [comment]
Let me make this clear:
- The ToS do not say that.  Here's the link: https://help.github.com/articles/github-terms-of-service
- The signup page does say, "free for open-source".  It does not say "free for open-source only" or use the word "strictly".  I agree this is a potential point to misunderstand, so...
- When someone mentioned it, I made sure to email GitHub directly.  Here it is:
  
  Hi - I'm running a project, non-commerical, but not open source (no source is available).  I'm currently using GitHub to host Downloads and Issues only - the repository is only used for a README file (created in the test and can be deleted if necessary).
  People have suggested that it's not allowable to use GitHub just for downloads and issues on a non-open-source project.  Is this the case?  - If so, what plan do I need?
  Thanks
  Kieren

Reply from Sonya @ GitHub:

```
Hi Kieren,

>People have suggested that it's not allowable to use GitHub just for
downloads and issues on a non-open-source project. Is this the case? - If
so, what plan do I need?

I use GitHub for knitting patterns. I don't think anything you're doing breaks our Terms of Service. You can always read them over if you're feeling nervous, but nothing says you have to have code in your repo.
```

http://help.github.com/terms-of-service/

```
Cheers,
Sonya
```

If you're looking for someone breaking terms of service, do you think it's:

a) The person who checked with his service provider to see if he was violating any terms, or:
b) The person who read the terms of service of a piece of software, saw the part "You agree not to reverse-engineer or modify the software.", clicked OK, then not only reverse-engineered the software, but posted the results for the world to see

If you're wanting to cause me aggro on my Christmas break, sending emails about false attribution and trolling on my project's site, it's working.  What pisses me off is that people and bullies in the name of "the community", and seem to spend so much time bitching about this project, that project, standards, lack of progress, etc., rather than actually being CONSTRUCTIVE.

Do yourself, and the rest of the community a favor, code some DCPU/0x10c stuff.

**Comment by jonpovey** [comment]
Your putdown amused me. Ignore the trolls, keep doing fun stuff.

**Pull request closed without merging**
